name: Publish to GitHub Packages (npm)

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  publish-gh:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@${{ github.repository_owner }}'
          always-auth: true
          cache: npm

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Verify GitHub Packages scope
        run: |
          node -e "const pkg=require('./package.json'); const owner=process.env.OWNER; if(!pkg.name.startsWith(`@${owner}/`)){ console.error(`\nPackage name '${pkg.name}' must start with @${owner}/ to publish to GitHub Packages for this repository.\nUpdate 'name' in package.json accordingly, or move the repo to match the scope.\n`); process.exit(1);} console.log('Scope OK:', pkg.name)"

      - name: Build
        run: npm run -s build

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --registry=https://npm.pkg.github.com

